[package]
name = "xtask"
version = "2.0.0"
edition = "2021"

[dependencies]
dotenvy = { workspace = true }
log = { workspace = true }
strum = { workspace = true }
tracel-xtask = { path = "../crates/tracel-xtask" }

[dev-dependencies]
rstest = { workspace = true }
